from dessins.ship import *
from dessins.plage import *
from dessins.verso import *
from dessins import *
from dessins.perroquet_male import *
from dessins.perroquet_femelle import *
from dessins.ane_femelle import *
from dessins.ane_male import *
from dessins.chat_femelle import *
from dessins.chat_male import *
from dessins.elephant_femelle import *
from dessins.elephant_male import *
from dessins.girafe_femelle import *
from dessins.girafe_male import *
from dessins.rino_femelle import *
from dessins.rino_male import *
from dessins.insecte_femelle import *
from dessins.insecte_male import *
from dessins.kangouroo_femelle import *
from dessins.kangouroo_male import *
from dessins.lion_femelle import *
from dessins.lion_male import *
from dessins.ours_femelle import *
from dessins.ours_male import *
from dessins.panda_femelle import *
from dessins.panda_male import *
